name: Update vcpkg baselines

on:
  schedule:
    - cron: 0 0 1 * *
  repository_dispatch:
    types: [update-baselines-event]
  workflow_dispatch:

permissions: write-all

concurrency:
  group: update-vcpkg-baselines
  cancel-in-progress: true

jobs:
  update-vcpkg-baselines:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'Starfield-Reverse-Engineering'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: python .github/update_vcpkg_baselines.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "ci: update vcpkg baselines"
