name: Update PDB

on:
  workflow_run:
    workflows: Maintenance
    types: completed
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: 5a38b5ec0eee3d1a1a6faab5e944617fee2697cf
  GITHUB_WORKSPACE: ${{ github.workspace }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Run CMake
        uses: lukka/run-cmake@v10.6
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CommonLibSF/CMakeLists.txt"
          configurePreset: build-debug-msvc-ninja
          configurePresetCmdString: "[`-B`, `$[env.GITHUB_WORKSPACE]/build`, `-S`, `$[env.GITHUB_WORKSPACE]/CommonLibSF`, `--preset`, `$[env.CONFIGURE_PRESET_NAME]`]"
          buildPreset: debug-msvc-ninja
          buildPresetCmdString: "[`--build`, `$[env.GITHUB_WORKSPACE]/build`, `--preset`, `$[env.BUILD_PRESET_NAME]`]"

      - name: Copy PDB
        run: |
          $pdb = Get-ChildItem -Path "${{ github.workspace }}" -Filter "CommonLibSF.pdb" -Recurse -ErrorAction SilentlyContinue -Force
          New-Item -Path "${{ github.workspace }}" -Name "pdb" -ItemType "directory" -ErrorAction SilentlyContinue
          Copy-Item "$pdb" -Destination "${{ github.workspace }}/pdb"

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "./pdb"
          message: "ci: update pdb"
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
